sudo: required
dist: trusty

language: node_js

node_js: "10"

addons:
  chrome: stable

branches:
  only:
  - master
  - develop

before_install:
- ARCHWIZARD_VERSION=$(grep '"angular-archwizard":' package.json | cut -d '"' -f4 | tr -d '[[:space:]]')
- if [[ "$ARCHWIZARD_VERSION" == *develop ]]; then
     ARCHWIZARD_LOCATION=$TRAVIS_BUILD_DIR/../angular-archwizard;
     git clone https://github.com/madoar/angular-archwizard.git $ARCHWIZARD_LOCATION;
     cd $ARCHWIZARD_LOCATION;
     npm install;
     npm run build;
     cd $TRAVIS_BUILD_DIR;
     npm install --save $ARCHWIZARD_LOCATION/dist;
  fi
